services:
  web:
    type: web
    name: workshop-todolist
    runtime: ruby
    plan: free
    buildCommand: bundle install
    startCommand: bin/dev
    healthCheckPath: /up
    disk:
      name: rails-storage
      mountPath: /rails/storage
      sizeGB: 1
    envVars:
    - Key: RAILS_MASTER_KEY
      sync: false